### ISSUE TITLE
AR_MATRIX_CODE_3x3_HAMMING63 is not defined anywhere

### ISSUE THREAD

**Issue by felixniemeyer** [andypotato/artoolkit5-js#23]
I'd like to use AR_MATRIX_CODE_3x3_HAMMING63 markers. 
There is no documentation or demo that sets any AR_MATRIX_CODE... as marker type.

There is a line in a cpp file
```
lib/ARBindEM.cpp:	constant("AR_MATRIX_CODE_3x3_HAMMING63", AR_MATRIX_CODE_3x3_HAMMING63 + 0);
```

But I don't know how these constants are exposed when importing artoolkit5-js.

**Comment by kalwalt** [comment]
Hi @felixniemeyer i added support for other Barcode types in our AR-js-org fork in this [PR 17](https://github.com/AR-js-org/artoolkit5-js/pull/17) but not for that type. I have to check if It Is possibile to add the type you mentioned.

**Comment by kalwalt** [comment]
I forgot that i added all the types, so @felixniemeyer if you want you can try our fork (  but use AR-js-org branch), and @andypotato maybe we could merge this in artooolkit5-js `master` branch?

**Comment by felixniemeyer** [comment]
Hi @kalwalt, 

thanks for pointing to the`AR-js-org branch.
I think I'll go with simply copying the integer value from your code and using that. 

I assume these `constant(...)` calls in the cpp expose these variables somewhere in the resulting js/wasm artifact. That would be even cleaner than having a second source of truth via an explicit `typedef enum { ... }`. Imagine the underlying cpp project chaning the values (not very probable) - you'd have to edit the `enum`, too.

**Comment by felixniemeyer** [comment]
Hi @kalwalt , 

thanks for your response. 
I found out, that artoolkit5-js defines a global variable `artoolkit` on which all the constants are defined: 

```
console.log(artoolkit.AR_MATRIX_CODE_3x3_HAMMING63) // outputs 515
``` 

I also read somewhere in the code, that this global variable design is not something that @andypotato chose but he's kind of forced to keep it this way because of previous work he is building on. 

Thanks everyone

**Comment by felixniemeyer** [comment]
If you're using typescript like I am, you might want to add this to your shims or any `.d.ts` file: 
```
declare var artoolkit: any;
```
This will tell the tsc, that `artoolkit` exists.

**Comment by kalwalt** [comment]
> If you're using typescript like I am, you might want to add this to your shims or any `.d.ts` file: 
> ```
> declare var artoolkit: any;
> ```
> This will tell the tsc, that `artoolkit` exists. 

Thank you for the suggestion!
The global `artoolkit` variable Is required because when a marker is deteced and tracked a `markerInfo` object is updated with all data( id, Matrix...) This because as It was designed It Is attached to the global `artoolkit` variable inside an **EM_ASM** struct. To avoid this we should change drastically the C Emscripten wrapper code, with a function that the return that object instead of void.

**Comment by andypotato** [comment]
@kalwalt I can merge it, just create a PR

**Comment by kalwalt** [comment]
> @kalwalt I can merge it, just create a PR

Ok i will send a PR when i can.🙂
