### ISSUE TITLE
Implement addNFTMarker

### ISSUE THREAD

**Issue by andypotato** [andypotato/artoolkit5-js#4]
Currently the [addNFTMarker](https://github.com/andypotato/artoolkit5-js/blob/4961c0cbabb4b5c77cb40adfa1be8efa658bafd6/src/ARToolkit.js#L126) is not implemented. Need to port the code from [here](https://github.com/kalwalt/jsartoolkit5/blob/244b2b23286403e78fa24805b34509dc5a88052f/js/artoolkit.api.js#L1881).

**Comment by kalwalt** [comment]
@andypotato I'm trying to solve this with a `Promise.all` but not works:

```javascript
async addNFTMarker (arId, urlOrData) {
    const target = '/markerNFT_' + this.markerNFTCount++

    let data
    let filename1 = urlOrData + '.fset'
    let filename2 = urlOrData + '.iset'
    let filename3 = urlOrData + '.fset3'

    if (urlOrData.indexOf('\n') !== -1) {
      data = Promise.all([
        Utils.string2Uint8Data(filename1),
        Utils.string2Uint8Data(filename2),
        Utils.string2Uint8Data(filename3)
      ])
    } else {
      // fetch data via HTTP
      try {
        data = await Promise.all([
          Utils.fetchRemoteData(filename1),
          Utils.fetchRemoteData(filename2),
          Utils.fetchRemoteData(filename3)
        ])
      } catch (error) { throw error }
    }

    this._storeDataFile(data, target)

    // return the internal marker ID
    return this.instance._addNFTMarker(arId, target)
  }
```
Maybe is better to implement a chained request directly with axios?

**Comment by kalwalt** [comment]
I am working on this branch https://github.com/kalwalt/artoolkit5-js/tree/feature-NFT

**Comment by andypotato** [comment]
This feature has been implemented by @MikiDi and has been merged into the master branch. Thanks a million @MikiDi !
